# Generated by Django 3.1 on 2020-08-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='url_image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ManyToManyField(related_name='listas_for_listing', to='auctions.Auction_listing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_de_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
