# Generated by Django 3.1 on 2020-08-21 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200821_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='user',
        ),
        migrations.AddField(
            model_name='lista',
            name='user',
            field=models.ManyToManyField(related_name='lista_de_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
