# Generated by Django 3.1 on 2020-08-22 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_lista_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='starting_bid',
            new_name='price',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_for_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_for_listing', to='auctions.auction_listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_for_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_listing', to='auctions.auction_listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lista',
            name='user',
            field=models.ManyToManyField(related_name='listas_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
