# Generated by Django 3.1 on 2020-08-22 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200822_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='listing',
        ),
        migrations.AddField(
            model_name='lista',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listas_for_listing', to='auctions.auction_listing'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lista',
            name='user',
        ),
        migrations.AddField(
            model_name='lista',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listas_for_user', to='auctions.user'),
            preserve_default=False,
        ),
    ]
